#ifndef CONFIG_H_
#define CONFIG_H_

#define FATFS_USE_DETECT_PIN		0
#define FATFS_SDIO_4BIT				1

#define FATFS_USE_WRITEPROTECT_PIN	0

#define FATFS_USE_DETECT_PIN_RCC	RCC_AHB1Periph_GPIOC
#define FATFS_USE_DETECT_PIN_PORT	GPIOC
#define FATFS_USE_DETECT_PIN_PIN	GPIO_Pin_6

#endif /* CONFIG_H_ */
